# .streamlit/config.toml
[server]
headless = true
address = "0.0.0.0"
port = 8501
baseUrlPath = "grafica"      # <- servirá en /grafica
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
